# Generated by Django 3.2.2 on 2021-05-13 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 17, 35, 4, 268620, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
